# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pb/user.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rpb/user.proto\x12\x04user\"\x06\n\x04Null\"\x18\n\x08UserName\x12\x0c\n\x04name\x18\x01 \x01(\t\"0\n\x04User\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03\x61ge\x18\x02 \x01(\x05\x12\r\n\x05hobby\x18\x03 \x01(\t\"(\n\x08UserList\x12\x1c\n\x08userlist\x18\x01 \x03(\x0b\x32\n.user.User2\x85\x01\n\nUserHandle\x12)\n\x0bGetUserList\x12\n.user.Null\x1a\x0e.user.UserList\x12%\n\x07GetUser\x12\x0e.user.UserName\x1a\n.user.User\x12%\n\x07\x41\x64\x64User\x12\n.user.User\x1a\x0e.user.UserListb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pb.user_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NULL']._serialized_start=23
  _globals['_NULL']._serialized_end=29
  _globals['_USERNAME']._serialized_start=31
  _globals['_USERNAME']._serialized_end=55
  _globals['_USER']._serialized_start=57
  _globals['_USER']._serialized_end=105
  _globals['_USERLIST']._serialized_start=107
  _globals['_USERLIST']._serialized_end=147
  _globals['_USERHANDLE']._serialized_start=150
  _globals['_USERHANDLE']._serialized_end=283
# @@protoc_insertion_point(module_scope)
